import Head from 'next/head'
import { useEffect, useCallback } from 'react'
// import Image from 'next/image'
// CAROUSEL Import
import useEmblaCarousel from 'embla-carousel-react'
import Autoplay from 'embla-carousel-autoplay'

import Header from './components/Header'

import { Inter } from '@next/font/google'
import Chevron from './components/Chevrons'
import styles from '../styles/Home.module.css'

import testImage from '../public/homepage-images/earrings-main.webp'
import aboutUsImage from '../public/homepage-images/about-us.webp'
import Footer from './components/Footer'



export default function Home() {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <Carousel />
      <FeaturedProducts />
      <Categories />
      <AboutUs />
      <Banner />
      <Footer />
    </>
  )
}

// HOMEPAGE - SLIDER ----------------
// Carousel Options
const autoplayOptions = {
  delay: 4000  ,
}

function Carousel() {
  const [emblaRef, emblaApi] = useEmblaCarousel({loop:true, draggable: false}, [
    // Autoplay(autoplayOptions),
  ])

  const scrollPrev = useCallback(() => {
    if (emblaApi) emblaApi.scrollPrev()
  }, [emblaApi])

  const scrollNext = useCallback(() => {
    if (emblaApi) emblaApi.scrollNext()
  }, [emblaApi])

  return (
    <section className={styles.carousel}>
      <div className={styles.carousel__viewport} ref={emblaRef}>
        <div className={styles.carousel__container}>
          <div className={styles.carousel__slide}>Slide 1</div>
          <div className={styles.carousel__slide}>Slide 2</div>
          <div className={styles.carousel__slide}>Slide 3</div>
        </div>
        <button className={styles.carousel__prev} onClick={scrollPrev}>
          <Chevron />
      </button>
      <button className={styles.carousel__next} onClick={scrollNext}>
      <Chevron />
      </button>
      </div>
  </section>
  )
}
// END OF HOMEPAGE - SLIDER ----------------

// HOMEPAGE - FEATURED PRODUCTS
function FeaturedProducts() {
  const [emblaRef, emblaApi] = useEmblaCarousel({align: 'start', draggable: false})

  useEffect(() => {
    if (emblaApi) {
      // Embla API is ready
    }
  }, [emblaApi])

  return (
    <section className={styles.featured}>
      <h2>Featured Products</h2>
      <div className={styles['carousel-products']} ref={emblaRef}>
        <div className={styles['carousel-products__container']}>
          <FeaturedPorductTemplate />
          <FeaturedPorductTemplate />
          <FeaturedPorductTemplate />
          <FeaturedPorductTemplate />
        </div>
      </div>
    </section>
  )
}

function FeaturedPorductTemplate(props) {
  return (
    <div className={styles['carousel-products__product']}>
      <img height={250} width={250} src={testImage.src}/>
      <div className={styles['product-description']}>
        <h5>Product Title</h5>
        <p>$12.22</p>
      </div>
    </div>  
  )
}
// END OF HOMEPAGE - FEATURED PRODUCTS-------------

// HOMEPAGE - CATEGORIES SECTION
function Categories() {
  return (
    <section className={styles['catagories-section']}>
      <h2>Categories</h2>
      <div className={styles.catagories}>
        <a className={styles['category-one']}>Category One</a>
        <a className={styles['category-two']}>Category Two</a>
        <a className={styles['category-three']}>Category Three</a>
        <a className={styles['category-four']}>Category Four</a>
      </div>
    </section>
  )
}
// END OF HOMEPAGE - CATEGORIES -------------

// HOMEPAGE -- BANNER------------

function Banner() {
  return (
    <section className={styles.banner}>
      <div className={styles['banner-container']}>
          <h3>Banner Text Here</h3>
          <button>Button</button>
      </div>
    </section>
  )
}

// END OF HOMEPAGE -- BANNER------------

// HOMEPAGE -- BANNER------------
function AboutUs() {
  return (
    <section className={styles.aboutus}>
      <div className={styles['aboutus-text']}>
        <h2>About Us</h2>
        <h3>Sub Heading Here</h3>
        <p> simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
      </div>
      <div className={styles['aboutus-image']}>
        <img src={aboutUsImage.src} height="500" width="500" alt="image of jewellery"/>
      </div>
    </section>
  )
}

// END OF HOMEPAGE -- BANNER------------